// sw.js — keeps the whole game on the tablet so it opens without internet.
// Generated by tools/build-sw.mjs; do not edit by hand.
const VERSION = '966fead3a8c2';
const CACHE = `maths-pets-${VERSION}`;
const FONT_CACHE = 'maths-pets-fonts';
const FILES = [
  "./",
  "index.html",
  "styles.css",
  "manifest.webmanifest",
  "assets/icon-192.png",
  "assets/icon-512.png",
  "js/app.js",
  "js/catalog.js",
  "js/config.js",
  "js/maths.js",
  "js/petBrain.js",
  "js/progress.js",
  "js/reporter.js",
  "js/rewards.js",
  "js/sound.js",
  "js/storage.js",
  "js/walk.js",
  "js/ui/dom.js",
  "js/ui/home.js",
  "js/ui/hub.js",
  "js/ui/keypad.js",
  "js/ui/pets.js",
  "js/ui/shop.js",
  "js/ui/start.js",
  "js/ui/walkScreen.js",
  "js/ui/zoomies.js",
  "assets/sounds/bark1.mp3",
  "assets/sounds/bark2.mp3",
  "assets/sounds/cat1.mp3",
  "assets/sounds/giraffe1.mp3",
  "assets/sounds/giraffe2.mp3",
  "assets/sounds/koala1.mp3",
  "assets/sounds/raccoon1.mp3",
  "assets/friends/biscuit.webp",
  "assets/friends/pepper.webp",
  "assets/friends/noodle.webp",
  "assets/friends/mittens.webp",
  "assets/friends/ginger.webp",
  "assets/friends/luna.webp",
  "assets/friends/gigi.webp",
  "assets/friends/stretch.webp",
  "assets/friends/sunny.webp",
  "assets/friends/kiki.webp",
  "assets/friends/gumnut.webp",
  "assets/friends/snooze.webp",
  "assets/friends/bandit.webp",
  "assets/friends/pip.webp",
  "assets/friends/rocky.webp",
  "assets/friends/sleep/biscuit.webp",
  "assets/friends/sleep/pepper.webp",
  "assets/friends/sleep/noodle.webp",
  "assets/friends/sleep/mittens.webp",
  "assets/friends/sleep/ginger.webp",
  "assets/friends/sleep/luna.webp",
  "assets/friends/sleep/gigi.webp",
  "assets/friends/sleep/stretch.webp",
  "assets/friends/sleep/sunny.webp",
  "assets/friends/sleep/kiki.webp",
  "assets/friends/sleep/gumnut.webp",
  "assets/friends/sleep/snooze.webp",
  "assets/friends/sleep/bandit.webp",
  "assets/friends/sleep/pip.webp",
  "assets/friends/sleep/rocky.webp",
  "assets/items/sofa.webp",
  "assets/items/rug.webp",
  "assets/items/lamp.webp",
  "assets/items/bookshelf.webp",
  "assets/items/dogbed.webp",
  "assets/items/cattower.webp",
  "assets/items/piano.webp",
  "assets/items/fishtank.webp",
  "assets/items/plant.webp",
  "assets/items/cushions.webp",
  "assets/items/tree.webp",
  "assets/items/swing.webp",
  "assets/items/pond.webp",
  "assets/items/flowers.webp",
  "assets/items/kennel.webp",
  "assets/items/trampoline.webp",
  "assets/items/bench.webp",
  "assets/items/mushrooms.webp",
  "assets/items/treehouse.webp",
  "assets/items/picnic.webp",
  "assets/rooms/living.webp",
  "assets/rooms/garden.webp"
];

self.addEventListener('install', e => {
  // cache: 'reload' skips the browser's HTTP cache, so a quick second deploy never stores the previous files.
  e.waitUntil(caches.open(CACHE).then(c => c.addAll(FILES.map(f => new Request(f, { cache: 'reload' })))).then(() => self.skipWaiting()));
});

self.addEventListener('activate', e => {
  e.waitUntil(caches.keys()
    .then(keys => Promise.all(keys.filter(k => k !== CACHE && k !== FONT_CACHE).map(k => caches.delete(k))))
    .then(() => self.clients.claim()));
});

self.addEventListener('fetch', e => {
  const req = e.request;
  if (req.method !== 'GET') return;
  const url = new URL(req.url);
  if (url.hostname.endsWith('supabase.co')) return;
  if (url.hostname === 'fonts.googleapis.com' || url.hostname === 'fonts.gstatic.com') {
    e.respondWith(caches.open(FONT_CACHE).then(async c => {
      const hit = await c.match(req);
      if (hit) return hit;
      const res = await fetch(req);
      c.put(req, res.clone());
      return res;
    }));
    return;
  }
  if (url.origin !== self.location.origin) return;
  e.respondWith(caches.match(req, { ignoreSearch: true }).then(hit => hit || fetch(req)));
});
