// Writes sw.js. The cache version is a hash of every cached file, so any change to the game
// gives the tablet a new version. tests/sw.test.js fails when sw.js is out of date.
// Run: node tools/build-sw.mjs
import fs from 'node:fs';
import crypto from 'node:crypto';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');

export async function swSource() {
  const { FRIENDS, ITEMS, ROOMS } = await import(path.join(root, 'js/catalog.js'));
  const list = dir => fs.readdirSync(path.join(root, dir)).filter(f => f.endsWith('.js')).sort().map(f => `${dir}/${f}`);
  const files = ['index.html', 'styles.css', 'manifest.webmanifest', 'assets/icon-192.png', 'assets/icon-512.png',
    ...list('js'), ...list('js/ui'),
    ...fs.readdirSync(path.join(root, 'assets/sounds')).filter(f => f.endsWith('.mp3')).sort().map(f => `assets/sounds/${f}`),
    ...FRIENDS.map(f => `assets/friends/${f.id}.webp`), ...FRIENDS.map(f => `assets/friends/sleep/${f.id}.webp`), ...ITEMS.map(i => `assets/items/${i.id}.webp`), ...ROOMS.map(r => `assets/rooms/${r.id}.webp`)];
  const hash = crypto.createHash('sha256');
  for (const f of files) hash.update(f).update(fs.readFileSync(path.join(root, f)));
  const version = hash.digest('hex').slice(0, 12);
  return `// sw.js — keeps the whole game on the tablet so it opens without internet.
// Generated by tools/build-sw.mjs; do not edit by hand.
const VERSION = '${version}';
const CACHE = \`maths-pets-\${VERSION}\`;
const FONT_CACHE = 'maths-pets-fonts';
const FILES = ${JSON.stringify(['./', ...files], null, 2)};

self.addEventListener('install', e => {
  // cache: 'reload' skips the browser's HTTP cache, so a quick second deploy never stores the previous files.
  e.waitUntil(caches.open(CACHE).then(c => c.addAll(FILES.map(f => new Request(f, { cache: 'reload' })))).then(() => self.skipWaiting()));
});

self.addEventListener('activate', e => {
  e.waitUntil(caches.keys()
    .then(keys => Promise.all(keys.filter(k => k !== CACHE && k !== FONT_CACHE).map(k => caches.delete(k))))
    .then(() => self.clients.claim()));
});

self.addEventListener('fetch', e => {
  const req = e.request;
  if (req.method !== 'GET') return;
  const url = new URL(req.url);
  if (url.hostname.endsWith('supabase.co')) return;
  if (url.hostname === 'fonts.googleapis.com' || url.hostname === 'fonts.gstatic.com') {
    e.respondWith(caches.open(FONT_CACHE).then(async c => {
      const hit = await c.match(req);
      if (hit) return hit;
      const res = await fetch(req);
      c.put(req, res.clone());
      return res;
    }));
    return;
  }
  if (url.origin !== self.location.origin) return;
  e.respondWith(caches.match(req, { ignoreSearch: true }).then(hit => hit || fetch(req)));
});
`;
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  fs.writeFileSync(path.join(root, 'sw.js'), await swSource());
  console.log('sw.js written');
}
